import React, {FC} from 'react';
import Head from "next/head";

interface IHeaderMeta {
    title: string
    description?: string
}

export const HeaderMeta:FC<IHeaderMeta> = ({title, description}) => {
    return (
        <Head>
            <title>{title}</title>
            <meta name="description" content={description || "Generated by create next app"}/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
    );
};
